name: Bundle CSS

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout https://github.com/carnarez/markdown-render-styling repository
        uses: actions/checkout@v3

      - name: Set up Python v3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir ghp-import

      - name: Set up Node v16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Node dependencies
        run: |
          npm install --global --no-audit --no-fund \
            autoprefixer \
            stylelint \
            postcss-cli

      - name: Bundle everything together
        run: |
          stylelint --config stylelint.json
          postcss style.css --replace --use autoprefixer
          postcss style.css --replace --use autoprefixer

      - name: Push bundle to branch
        run: |
          ghp-import --branch css --force --push style.css
